# Generated by Django 4.1.7 on 2023-03-24 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, verbose_name='логин')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия пользователя')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон номера')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_picture', verbose_name='Аватар')),
                ('sex', models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], default='Male', max_length=100, verbose_name='Пол')),
                ('bio', models.TextField(max_length=3000, verbose_name='Биография пользователя')),
                ('subscribers_count', models.PositiveIntegerField(default=0, verbose_name='Количество подписчиков')),
                ('subscriptions_count', models.PositiveIntegerField(default=0, verbose_name='Количество подписок')),
                ('publications_count', models.PositiveIntegerField(default=0, verbose_name='Количество публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль пользователя')),
            ],
        ),
    ]
