# Generated by Django 4.1.7 on 2023-03-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='point',
            field=models.CharField(max_length=255, verbose_name='Местоположения'),
        ),
    ]
