# Generated by Django 4.1.7 on 2023-03-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0004_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='user_picture', verbose_name='Изображения'),
        ),
    ]
