# Generated by Django 4.1.7 on 2023-03-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='user_picture/', verbose_name='Изображения'),
        ),
    ]
